"use client";

import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { suiteConfig } from "@/config/suite";

interface LoadingScreenProps {
  fullScreen?: boolean;
}

export default function LoadingScreen({ fullScreen = false }: LoadingScreenProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [mounted, setMounted] = useState(false);
  const pathname = usePathname();

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted || !containerRef.current) return;

    let anim: any;

    // Import lottie-web dynamically inside useEffect to ensure it strictly initializes on the client
    import("lottie-web").then((lottieModule) => {
      const lottie = lottieModule.default || lottieModule;

      if (containerRef.current) {
        anim = lottie.loadAnimation({
          container: containerRef.current,
          renderer: "svg",
          loop: true,
          autoplay: true,
          path: "/animations/crestone_motion.json",
        });
      }
    });

    return () => {
      if (anim) anim.destroy();
    };
  }, [mounted]);

  const containerClass = fullScreen
    ? "fixed inset-0 z-[9999] flex flex-col items-center justify-center bg-[var(--color-container)] transition-all duration-300"
    : "flex flex-col items-center justify-center w-full h-full min-h-[300px]";

  if (!mounted) {
    return <div className={containerClass} />;
  }

  // Determine branch color based on current path
  const branchId = pathname?.split("/")[1];
  const branch = suiteConfig.branches.find((b) => b.id === branchId);
  const branchColor = branch?.color || "var(--color-neutral-400)";

  // We use Tailwind arbitrary variants to target the paths generated by lottie-web.
  // The Lottie JSON uses rgb(217,217,217) for light grey (animating circles), 
  // rgb(15,23,43) for dark blue (main logo), and rgb(252,252,252) for the static circles.
  // We override them with the branch color, the seidor main text color, and the neutral container color!
  const lottieColorOverrideClasses =
    "[&_path[fill^='rgb(217']]:!fill-[var(--loading-branch-color)] [&_path[stroke^='rgb(15']]:!stroke-[var(--color-seidor-main-text)] [&_path[fill^='rgb(252']]:!fill-[var(--color-container)]";

  return (
    <div className={containerClass}>
      <div
        className={`w-48 h-48 sm:w-64 sm:h-64 flex items-center justify-center ${lottieColorOverrideClasses}`}
        ref={containerRef}
        style={{ "--loading-branch-color": branchColor } as React.CSSProperties}
      />
      {/* Optional helper text */}
      <p className="mt-4 text-sm font-medium text-neutral-800 dark:text-neutral-200 font-poppins animate-pulse">
        {branch ? `Iniciando Crestone ${branch.title}...` : "Cargando módulo..."}
      </p>
    </div>
  );
}

